<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">

<html lang="en">

 <head>

  <title>Cameron Allett's Home Page</title>

  <style type="text/css"><!--

    /* This sets up the line that appears below the header */
    h1 { border-bottom: medium solid; }
    .footer { border-top: thin solid; }

    /* Next, the colours: */
    body { background: #ccfff9; color: black; } /* main page */
    :link { background: transparent; color: blue; } /* unvisited links */
    :visited { background: transparent; color: purple; } /* visited links */
    :link:hover, :visited:hover, :link:active, :visited:active
      { background: transparent; color: red; } /* active links */
    /* The next line sets the colour of the main header */
    h1 { background: transparent; color: #080cff; border-color: #000000; }
    /* And the following line sets the colour of the "definition terms".
    See the content below for more information. */
    dt { background: transparent; color: #080cff; }
    h2 { color: #080cff; }

    /* The paddings and margins */
    .footer { padding: 0.1em 0.2em; }
    dt { margin-top: 0.5em; }

    /* Next we'll set the fonts */
    body { font-family: Verdana, Arial, sans-serif; }
    h1 { font-weight: 100; letter-spacing: 0.25em; }
    dt { font-weight: bold; display: run-in; }
    h2 { font-weight: bold; display: run-in; font-size: 1em; margin-top: 1em; margin-bottom: 1em; }
    .footer { font-size: smaller; font-style: italic; }

    /* Finally, if you add a picture, we'll just make sure it floats
    to the right of the page */
    p img { float: right; }

  --></style>

  <meta name="generator" content="This page was generated by the Bath University 'mkhome' script, based on a template by Ian Hickson (py8ieh=mkhome@bath.ac.uk).">

  <script src="quotesScript.js"></script>

 </head>

 <body onload="onLoad()">

  <h1>Cameron Allett</h1>

  <!-- To add a picture of yourself:
     1. Get an image.
     2. Put it into this file: ~ca821/public_html/photo.gif.
     3. Make the file available for reading by others. To do this
        type: chmod og+r ~ca821/public_html/photo.gif
        ...at a UNIX shell prompt.
     4. Add the following line after these comments:
        <p><img src="photo.gif" title="My face!" alt=""></p>
        The text in between the quotes after the "alt=" bit is what is
        seen by folks without images or using text-only viewing
        devices such as lynx. For decorative images it should probably
        be nothing, for information images such as diagrams it should
        be the textual representation of that image (not usually a
        description!). The 'title' attribute says what should appear
        when the mouse cursor hovers over the image.
  -->

  <h2 align="center">Today's Thought</h2>
  <p align="center" id="quoteText">Enable Javascript!</p>
  <p align="center" id="quoteAuthor"></p>
  <br />

  <dl>

	<dt>About me</dt>
	<dd>I am a PhD student in the <a href="https://www.bath.ac.uk/projects/mathematical-foundations-of-computation/">Mathematical Foundations of Computation</a> group at the University of Bath, doing research in proof theory. I began my studies in October 2021, with funding from an EPSRC studentship. My supervisor is <a href="http://willem.heijltj.es//">Willem Heijltjes</a>.
	<br /><br />
	Previously, I completed a BA and MMath in <a href="https://www.ox.ac.uk/admissions/undergraduate/courses-listing/mathematics">Mathematics</a> at the University of Oxford.</dd>

    <dt>Conference Publications</dt>
    <dd>I presented my work on the epsilon-calculus in deep inference at <a href="https://lics.siglog.org/lics24/">LICS 2024</a> in Tallinn, Estonia on 8 July 2024. (<a href="/ca821/LICS24-116.pdf">pdf</a>)</dd>

	<dt>Talks</dt> <dd><a href="https://www.cs.ox.ac.uk/seminars/2653.html"><i>Non-elementary compression of first-order proofs in deep inference using epsilon-terms</i></a>, presented at the <a href="https://www.cs.ox.ac.uk/seminars/oasis/">The Oxford Advanced Seminar on Informatic Structures</a> on 31 May 2024. (<a href="/ca821/OASIS31-05-24.pdf">slides</a>)</dd>
<br />
<dd><i>Compressing first-order proofs in deep inference using epsilon-terms</i>, presented at the <a href="https://www.anupamdas.com/sls3/">Southern Logic Seminar</a> in Birmingham, England on 5 September 2023.</dd>

	<dt>Events</dt> <dd>I attended the <a href="https://www.mathematik.uni-muenchen.de/~schwicht/pc23.php">Proof and Computation Autumn School</a> in Herrsching, Germany from 10 - 16 September 2023.</dd>
	<br />
	<dd>I attended the <a href="https://uswpt.sites.uu.nl/">Proof Society Autumn School and Workshop 2022</a> in Utrecht, The Netherlands from 7 - 12 November 2022.</dd>
	<br />
	<dd>I attended the <a href="https://www.cs.nott.ac.uk/~psznk/events/mgs22.html">Midlands Graduate School in the Foundations of Computing Science</a> in Nottingham, England from 10 - 14 April 2022.</dd>
	<br />
	<dd>I attended the <a href="https://conferences.cirm-math.fr/2685.html">Linear Logic Winter School</a> as part of Logic and Interactions 2022 at CIRM in Marseille, France from 24 - 28 January 2022.</dd>

	<dt>Teaching</dt> <dd>I teach on the <i>Functional Programming</i>, <i>Foundations of Computation</i> and <i>Programming 1</i> modules.</dd>

  <dt>Email</dt> <dd><a href="mailto:ca821@bath.ac.uk">ca821@bath.ac.uk</a></dd>
  </dl>

  <p class="footer"></p>

 </body>

</html>
